package com.viettel.imdb.rest.exception;

/**
 * @author longdt20
 * @since 17:15 18/02/2019
 */

public enum RestErrorCode {
    SOMETHING_WENT_WRONG,
    OK,
    NAMESPACE_NOT_EXIST,
    ONLY_SUPPORT_ONE_FIELD,
    PARAMETER_RECORD_REQUIRED,
    PARAMETER_KEY_REQUIRED,
    FILTER_NOT_IN_CORRECT_FORMAT,
    FILTER_RANGE_INVALID,
    TABLENAME_LENGTH_INVALID,
    DATA_NOT_IN_CORRECT_FORMAT,
    UNEXPECTED_ERROR_OCCURRED,
    WRONG_JSON_FORMAT,
    PRIVILEGE_TYPE_NOT_EXIST,
    INVALID_USERNAME,
    INVALID_PASSWORD,
    MISSING_INFORMATION,
    PARENT_ROLE_NOT_EXIST,
    USERNAME_EXIST,
    USER_NOT_EXIST,
    NODE_NOT_EXIST,
    NODE_EXIST
}
